services:
  valkey:
    image: valkey/valkey:7.2.5
    restart: unless-stopped
    labels:
      traefik.enable: false

  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    expose:
      - "3000"
      - "50051"
    ports:
      - "127.0.0.1:3000:3000/tcp"
    # depends_on:
    #   - valkey
    #   - identity
    restart: unless-stopped
    environment:
      ISSUERS_OEM_DID: ${ISSUERS_OEM_DID}
      ISSUERS_OEM_FRAGMENT: ${ISSUERS_OEM_FRAGMENT}
      ISSUERS_TA_DID: ${ISSUERS_TA_DID}
      ISSUERS_TA_FRAGMENT: ${ISSUERS_TA_FRAGMENT}
      ISSUERS_PSP_DID: ${ISSUERS_PSP_DID}
      ISSUERS_PSP_FRAGMENT: ${ISSUERS_PSP_FRAGMENT}
      ISSUERS_PLO_DID: ${ISSUERS_PLO_DID}
      ISSUERS_PLO_FRAGMENT: ${ISSUERS_PLO_FRAGMENT}

  identity:
    image: iotaleger/identity-grpc
    # image: iotaledger/identity-grpc:alpha
    restart: unless-stopped
    environment:
      - API_ENDPOINT=https://api.testnet.shimmer.network
      - SNAPSHOT_PATH=/stronghold.hodl
      - STRONGHOLD_PWD_FILE=/run/secrets/stronghold_pwd
    volumes:
      - ./data/stronghold.hodl:/stronghold.hodl:ro
    expose:
      - "50051"
    labels:
      traefik.enable: false
    secrets:
      - stronghold_pwd

  oid4vc-tanglelabs:
    build:
      context: ./
      dockerfile: ./oid4vc/TangleLabs/Dockerfile
    restart: unless-stopped
    environment:
      RP_DID: ${ISSUERS_TA_DID}
      SIGNER_KEYID: ${ISSUERS_TA_KEYID}
      KEY_FRAGMENT: ${ISSUERS_TA_FRAGMENT}
      PUBLIC_URL: ${TA_PUBLIC_URL}
    expose:
      - "3333"
      - "50051"
    ports:
      - "${LOCAL_IP_ADDRESS}:3333:3333/tcp"
    volumes:
      - ./shared:/usr/shared

  # oid4vc-waltid:
  #   build:
  #     context: ./
  #     dockerfile: ./oid4vc/walt.id/Dockerfile
  #   restart: unless-stopped
  #   expose:
  #     - '3000'
  #     - '50051'
  #   ports:
  #     - "127.0.0.1:3001:3000/tcp"
  #   volumes:
  #     - ./shared:/usr/shared

  oid4vc-impierce:
    image: impiercetechnologies/ssi-agent:c25f9da
    depends_on:
      - cqrs-postgres-db
    restart: unless-stopped
    expose:
      - "3033"
    ports:
      - "${LOCAL_IP_ADDRESS}:3033:3033/tcp"
    volumes:
      - ./shared:/usr/shared
      - ./data/stronghold.hodl:/stronghold.hodl:ro
      - ./oid4vc/impierce/event_publisher_config.yml:/app/agent_event_publisher_http/config.yml:ro
      - ./oid4vc/impierce/config.yml:/app/agent_application/config.yml:ro
      - ./oid4vc/impierce/issuance_config.yml:/app/agent_issuance/issuance_config.yml:ro
      - ./data/tmp:/app/agent_api_rest
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "export AGENT_CONFIG_STRONGHOLD_PASSWORD=$$(cat /run/secrets/stronghold_pwd) ; /usr/local/bin/agent_application",
      ]
    environment:
      AGENT_CONFIG_URL: ${OEM_PUBLIC_URL}
      AGENT_SECRET_MANAGER_STRONGHOLD_PATH: /stronghold.hodl
      AGENT_CONFIG_ISSUER_KEY_ID: ${ISSUERS_OEM_KEYID}
      AGENT_CONFIG_ISSUER_DID: ${ISSUERS_OEM_DID}
      AGENT_CONFIG_ISSUER_FRAGMENT: ${ISSUERS_OEM_FRAGMENT}
      AGENT_CONFIG_DEFAULT_DID_METHOD: "did:iota:rms"
      AGENT_APPLICATION_ENABLE_CORS: true
      #AGENT_CONFIG_LOG_FORMAT: json
      AGENT_CONFIG_EVENT_STORE: postgres
      AGENT_STORE_DB_CONNECTION_STRING: postgresql://demo_user:demo_pass@cqrs-postgres-db:5432/demo
      #RUST_LOG: debug
    secrets:
      - stronghold_pwd

  cqrs-postgres-db:
    image: postgres
    restart: unless-stopped
    expose:
      - 5432
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
    volumes:
      - "./oid4vc/impierce/db:/docker-entrypoint-initdb.d"

secrets:
  stronghold_pwd:
    file: data/stronghold_secret.txt
